
import {tataNexon,hi20,skodaFabia,hi10M,rkwid, rkwidClimber, dgo, tx,bmw,re} from "../assets"

export const CarsData = [
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
        },
      {
        name: "Hyundai i20",
        image: hi20,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "18 km/1-liter",
        transmisson: "Manual",
        price : "0.5 Lakhs",  
        }, 
      {
        name: "Skoda Fabia",
        image: skodaFabia,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "19 km/1-liter",
        transmisson: "Manual",
        price : "2.5 Lakhs",  
      },
      {
        name: "Hyundai i10M",
        image: hi10M,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
        },
      {
        name: "Renault Kwid",
        image: rkwid,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
        }, 
      {
        name: "Renault Kwid Climber",
        image: rkwidClimber,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      }, 
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
        },
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
        }, 
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      }, 
      {
        name: "Datson Go",
        image: dgo,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
        },
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
        }, 
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      }, 
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
        },
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
        }, 
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      }, 
      {
        name: "Renault Kwid Climber",
        image: rkwidClimber,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      },
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
        }, 
      {
        name: "Tata Nexon",
        image: re,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      }, 
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
        },
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
        }, 
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      },
      {
        name: "Renault Kwid Climber",
        image: rkwidClimber,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs", 
      },
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      },
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      },
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      },
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      },
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      },
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      },
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      },
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      },
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      },
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      },
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      },
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      },
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      },
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      },
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      },
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      },
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      },
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      },
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      },
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      },
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      },
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      },
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      },
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      },
      {
        name: "Tata Nexon XG",
        image: tx,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      },
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      },
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      },
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      },
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      },
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      },
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      },
      {
        name: "BMW X3",
        image: bmw,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      },
      {
        name: "Tata Nexon",
        image: tataNexon,
        year: "2021",
        peoplenumber: "4",
        driven : "Petrol",
        kilometers: "15 km/1-liter",
        transmisson: "Manual",
        price : "7.5 Lakhs",  
      },

      
  ];